// <auto-generated />
using System;
using Bibliotech.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliotech.Infrastructure.Migrations
{
    [DbContext(typeof(BibliotechDbContext))]
    [Migration("20260805193714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("Bibliotech.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreExemplairesDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreExemplairesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auteur = "Antoine de Saint-Exupery",
                            NombreExemplairesDisponibles = 5,
                            NombreExemplairesTotal = 5,
                            RowVersion = new byte[0],
                            Titre = "Le Petit Prince"
                        },
                        new
                        {
                            Id = 2,
                            Auteur = "Albert Camus",
                            NombreExemplairesDisponibles = 3,
                            NombreExemplairesTotal = 3,
                            RowVersion = new byte[0],
                            Titre = "L'Etranger"
                        },
                        new
                        {
                            Id = 3,
                            Auteur = "Victor Hugo",
                            NombreExemplairesDisponibles = 6,
                            NombreExemplairesTotal = 6,
                            RowVersion = new byte[0],
                            Titre = "Les Miserables"
                        },
                        new
                        {
                            Id = 4,
                            Auteur = "Gustave Flaubert",
                            NombreExemplairesDisponibles = 2,
                            NombreExemplairesTotal = 2,
                            RowVersion = new byte[0],
                            Titre = "Madame Bovary"
                        },
                        new
                        {
                            Id = 5,
                            Auteur = "Emile Zola",
                            NombreExemplairesDisponibles = 4,
                            NombreExemplairesTotal = 4,
                            RowVersion = new byte[0],
                            Titre = "Germinal"
                        },
                        new
                        {
                            Id = 6,
                            Auteur = "Albert Camus",
                            NombreExemplairesDisponibles = 5,
                            NombreExemplairesTotal = 5,
                            RowVersion = new byte[0],
                            Titre = "La Peste"
                        },
                        new
                        {
                            Id = 7,
                            Auteur = "Victor Hugo",
                            NombreExemplairesDisponibles = 3,
                            NombreExemplairesTotal = 3,
                            RowVersion = new byte[0],
                            Titre = "Notre-Dame de Paris"
                        },
                        new
                        {
                            Id = 8,
                            Auteur = "Voltaire",
                            NombreExemplairesDisponibles = 4,
                            NombreExemplairesTotal = 4,
                            RowVersion = new byte[0],
                            Titre = "Candide"
                        },
                        new
                        {
                            Id = 9,
                            Auteur = "Guy de Maupassant",
                            NombreExemplairesDisponibles = 2,
                            NombreExemplairesTotal = 2,
                            RowVersion = new byte[0],
                            Titre = "Bel-Ami"
                        },
                        new
                        {
                            Id = 10,
                            Auteur = "Stendhal",
                            NombreExemplairesDisponibles = 5,
                            NombreExemplairesTotal = 5,
                            RowVersion = new byte[0],
                            Titre = "Le Rouge et le Noir"
                        },
                        new
                        {
                            Id = 11,
                            Auteur = "Jules Verne",
                            NombreExemplairesDisponibles = 4,
                            NombreExemplairesTotal = 4,
                            RowVersion = new byte[0],
                            Titre = "Voyage au centre de la Terre"
                        },
                        new
                        {
                            Id = 12,
                            Auteur = "Jules Verne",
                            NombreExemplairesDisponibles = 6,
                            NombreExemplairesTotal = 6,
                            RowVersion = new byte[0],
                            Titre = "Vingt mille lieues sous les mers"
                        },
                        new
                        {
                            Id = 13,
                            Auteur = "Alexandre Dumas",
                            NombreExemplairesDisponibles = 3,
                            NombreExemplairesTotal = 3,
                            RowVersion = new byte[0],
                            Titre = "Le Comte de Monte-Cristo"
                        },
                        new
                        {
                            Id = 14,
                            Auteur = "Alexandre Dumas",
                            NombreExemplairesDisponibles = 5,
                            NombreExemplairesTotal = 5,
                            RowVersion = new byte[0],
                            Titre = "Les Trois Mousquetaires"
                        },
                        new
                        {
                            Id = 15,
                            Auteur = "Andre Malraux",
                            NombreExemplairesDisponibles = 2,
                            NombreExemplairesTotal = 2,
                            RowVersion = new byte[0],
                            Titre = "La Condition humaine"
                        },
                        new
                        {
                            Id = 16,
                            Auteur = "Emile Zola",
                            NombreExemplairesDisponibles = 4,
                            NombreExemplairesTotal = 4,
                            RowVersion = new byte[0],
                            Titre = "Thérèse Raquin"
                        },
                        new
                        {
                            Id = 17,
                            Auteur = "Honore de Balzac",
                            NombreExemplairesDisponibles = 5,
                            NombreExemplairesTotal = 5,
                            RowVersion = new byte[0],
                            Titre = "Le Pere Goriot"
                        },
                        new
                        {
                            Id = 18,
                            Auteur = "Honore de Balzac",
                            NombreExemplairesDisponibles = 3,
                            NombreExemplairesTotal = 3,
                            RowVersion = new byte[0],
                            Titre = "Illusions perdues"
                        },
                        new
                        {
                            Id = 19,
                            Auteur = "George Orwell",
                            NombreExemplairesDisponibles = 4,
                            NombreExemplairesTotal = 4,
                            RowVersion = new byte[0],
                            Titre = "1984"
                        },
                        new
                        {
                            Id = 20,
                            Auteur = "Frank Herbert",
                            NombreExemplairesDisponibles = 2,
                            NombreExemplairesTotal = 2,
                            RowVersion = new byte[0],
                            Titre = "Dune"
                        });
                });

            modelBuilder.Entity("Bibliotech.Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantPenalite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Bibliotech.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DureePretJours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEmpruntsSimultanes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Profil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Martin",
                            Prenom = "Alice",
                            Profil = 1
                        },
                        new
                        {
                            Id = 2,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Dupont",
                            Prenom = "Thomas",
                            Profil = 2
                        },
                        new
                        {
                            Id = 3,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Bernard",
                            Prenom = "Julie",
                            Profil = 1
                        },
                        new
                        {
                            Id = 4,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Petit",
                            Prenom = "Lucas",
                            Profil = 1
                        },
                        new
                        {
                            Id = 5,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Robert",
                            Prenom = "Emma",
                            Profil = 2
                        },
                        new
                        {
                            Id = 6,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Richard",
                            Prenom = "Louis",
                            Profil = 1
                        },
                        new
                        {
                            Id = 7,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Durand",
                            Prenom = "Camille",
                            Profil = 2
                        },
                        new
                        {
                            Id = 8,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Moreau",
                            Prenom = "Hugo",
                            Profil = 1
                        },
                        new
                        {
                            Id = 9,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Simon",
                            Prenom = "Chloe",
                            Profil = 2
                        },
                        new
                        {
                            Id = 10,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Laurent",
                            Prenom = "Nathan",
                            Profil = 1
                        },
                        new
                        {
                            Id = 11,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Michel",
                            Prenom = "Sarah",
                            Profil = 1
                        },
                        new
                        {
                            Id = 12,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Garcia",
                            Prenom = "Antoine",
                            Profil = 2
                        },
                        new
                        {
                            Id = 13,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "David",
                            Prenom = "Manon",
                            Profil = 1
                        },
                        new
                        {
                            Id = 14,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Bertrand",
                            Prenom = "Paul",
                            Profil = 2
                        },
                        new
                        {
                            Id = 15,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Roux",
                            Prenom = "Lea",
                            Profil = 1
                        },
                        new
                        {
                            Id = 16,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Vincent",
                            Prenom = "Mathieu",
                            Profil = 1
                        },
                        new
                        {
                            Id = 17,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Fournier",
                            Prenom = "Clara",
                            Profil = 2
                        },
                        new
                        {
                            Id = 18,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Girard",
                            Prenom = "Julien",
                            Profil = 1
                        },
                        new
                        {
                            Id = 19,
                            DureePretJours = 28,
                            MaxEmpruntsSimultanes = 5,
                            Nom = "Andre",
                            Prenom = "Lucie",
                            Profil = 2
                        },
                        new
                        {
                            Id = 20,
                            DureePretJours = 21,
                            MaxEmpruntsSimultanes = 3,
                            Nom = "Mercier",
                            Prenom = "Baptiste",
                            Profil = 1
                        });
                });

            modelBuilder.Entity("Bibliotech.Domain.Entities.Loan", b =>
                {
                    b.HasOne("Bibliotech.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bibliotech.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
